name: makerslab_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^3.0.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  material_symbols_icons: ^4.2815.1
  go_router: ^16.0.0
  intl: ^0.19.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  logger: ^2.6.0
  package_info_plus: ^8.3.0
  lottie: ^3.3.1
  community_material_icon: ^5.9.55
  video_player: ^2.10.0
  youtube_player_flutter: ^9.1.2
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  share_plus: ^11.1.0
  path_provider: ^2.1.5
  flutter_chat_core: ^2.8.0
  flutter_chat_ui: ^2.9.0
  flutter_chat_types: ^3.6.2
  flyer_chat_image_message: ^2.2.1
  file_picker: ^10.3.2
  image_picker: ^1.2.0
  dio: ^5.9.0
  flyer_chat_file_message:
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon-128x128.png"
    background_color: "#247BA0"
    theme_color: "#247BA0"
  windows:
    generate: true
    image_path: "assets/icon/icon-128x128.png"
    icon_size: 128 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon-128x128.png"

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/brand/
    - assets/images/static/
    - assets/images/static/materials/
    - assets/images/static/temperature/
    - assets/images/static/temperature/instructions/
    - assets/images/static/servo/
    - assets/images/static/servo/instructions/
    - assets/images/static/light_control/
    - assets/images/static/light_control/instructions/
    - assets/images/static/gamepad/
    - assets/images/static/gamepad/instructions/
    - assets/files/
    - assets/lotties/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
